version:     "0018b--12-Sep-2021"
copyright:   "2021-2021"
description:
  This is a
  GitHub Page Template
disclaimer:
  I have spoken.
keywords:    "jekyll, testing"
navbarlinks:
- navbar:    "Home"
  link:      "/"
- navbar:    "MyLog"
  link:      "/TXT/mylog.txt"
- navbar:    "Tips"
  link:      "/TIPS/"
- navbar:    "Zip File"
  link:      "/template.zip"
- navbar:    "TarBall"
  link:      "/template.tar.bz2"
- navbar:    "GitHub"
  link:      "https://github.com/nafhansyandana/os212/"
- navbar:    "Listing"
  link:      "/000.html"
- navbar:    "About"
  link:      "/ABOUT/"
- navbar:    "GitHub Page"
  link:      "https://nafhansyandana.github.io/os212/"
title:       "Nafhan Raissa Syandana OS212 Github Page"
lang:        "en-US"
author:      "Nafhan Raissa Syandana"
address:     "Depok"
sitemap:     "true"
markdown:    "kramdown"
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata
plugins:
- jekyll-sitemap
- jekyll-seo-tag
google_analytics: "UA-89852122-15"

urlweb:           "https://template.vlsm.org/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/ThisIsHowMeDoIt/template"


